'use strict';

/**
 * Lambda@Edge function for Basic Authentication on CloudFront
 * This function intercepts viewer requests and requires Basic Auth credentials
 *
 * Credentials are injected at deploy time via Terraform templatefile()
 */

// Base64 encoded credentials: username:password
// Generated by Terraform: base64encode("${username}:${password}")
const VALID_CREDENTIALS = '${credentials_base64}';
const REALM = '${realm}';

exports.handler = async (event) => {
    const request = event.Records[0].cf.request;
    const headers = request.headers;

    // Check if Authorization header exists
    const authHeader = headers.authorization || headers.Authorization;

    if (!authHeader || authHeader.length === 0) {
        return unauthorized();
    }

    // Extract credentials from Authorization header
    const authValue = authHeader[0].value;

    // Check if it's Basic auth
    if (!authValue.startsWith('Basic ')) {
        return unauthorized();
    }

    // Extract base64 credentials
    const encodedCredentials = authValue.substring(6);

    // Validate credentials
    if (encodedCredentials !== VALID_CREDENTIALS) {
        return unauthorized();
    }

    // Credentials are valid, allow the request
    return request;
};

function unauthorized() {
    return {
        status: '401',
        statusDescription: 'Unauthorized',
        headers: {
            'www-authenticate': [{
                key: 'WWW-Authenticate',
                value: `Basic realm="${REALM}"`
            }],
            'content-type': [{
                key: 'Content-Type',
                value: 'text/html'
            }]
        },
        body: `
<!DOCTYPE html>
<html>
<head>
    <title>Authentication Required</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }
        .container {
            background: white;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            text-align: center;
            max-width: 400px;
        }
        h1 { color: #333; margin-bottom: 1rem; }
        p { color: #666; }
        .logo { font-size: 3rem; margin-bottom: 1rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">🔒</div>
        <h1>Authentication Required</h1>
        <p>This site is protected. Please enter your credentials to access TerraPerf.</p>
    </div>
</body>
</html>
        `
    };
}
